-- T16(제안 결정 D29): Instagram 모의 미디어 게시 — remote_steps 에 ig_container(post_index 0 = 게시할 컨테이너·1..n = 캐러셀 자식, created|finished|error)·
-- ig_publish(post_index 0, published) 종류, mock_scenarios 에 instagram_* 시나리오, oauth 공급자 CHECK 에 mock_instagram(Meta 형 모의 OAuth).
-- drizzle-kit 출력 그대로. remote_steps_guard 트리거·remote_id LIKE 'mock%' CHECK 는 바꾸지 않는다(live 어댑터 전 다시 정한다). 공개 미디어 URL 은 저장하지 않는다.
ALTER TABLE "mock_scenarios" DROP CONSTRAINT "mock_scenarios_scenario_chk";--> statement-breakpoint
ALTER TABLE "oauth_credentials" DROP CONSTRAINT "oauth_credentials_provider_chk";--> statement-breakpoint
ALTER TABLE "oauth_credentials" DROP CONSTRAINT "oauth_credentials_mock_chk";--> statement-breakpoint
ALTER TABLE "oauth_states" DROP CONSTRAINT "oauth_states_provider_chk";--> statement-breakpoint
ALTER TABLE "remote_steps" DROP CONSTRAINT "remote_steps_kind_chk";--> statement-breakpoint
ALTER TABLE "remote_steps" DROP CONSTRAINT "remote_steps_kind_status_chk";--> statement-breakpoint
ALTER TABLE "mock_scenarios" ADD CONSTRAINT "mock_scenarios_scenario_chk" CHECK ("mock_scenarios"."scenario" in ('success', 'success_public', 'processing_then_confirm', 'transient', 'transient_then_success', 'rate_limited', 'server_error_no_side_effect', 'server_error_side_effect_unknown', 'permanent', 'auth', 'ambiguous_sent', 'ambiguous_not_sent', 'hang', 'cancel_supported', 'reconcile_unsupported', 'threads_success', 'threads_container_slow', 'threads_publish_timeout_sent', 'threads_publish_timeout_not_sent', 'threads_thread_partial', 'threads_rate_limited', 'threads_token_invalid', 'threads_text_too_long', 'youtube_success_private', 'youtube_processing_slow', 'youtube_network_drop', 'youtube_response_lost_after_complete', 'youtube_session_expired_before_complete', 'youtube_quota_exceeded', 'youtube_token_invalid', 'youtube_rejected', 'youtube_public_unverified_forced_private', 'youtube_scheduled_private', 'youtube_project_verified', 'instagram_success', 'instagram_container_slow', 'instagram_publish_timeout_sent', 'instagram_publish_timeout_not_sent', 'instagram_rate_limited', 'instagram_token_invalid', 'instagram_permission_denied', 'instagram_invalid_spec_remote', 'instagram_container_error'));--> statement-breakpoint
ALTER TABLE "oauth_credentials" ADD CONSTRAINT "oauth_credentials_provider_chk" CHECK ("oauth_credentials"."provider" in ('mock_threads', 'threads', 'mock_google', 'mock_instagram'));--> statement-breakpoint
ALTER TABLE "oauth_credentials" ADD CONSTRAINT "oauth_credentials_mock_chk" CHECK ("oauth_credentials"."is_mock" = ("oauth_credentials"."provider" in ('mock_threads', 'mock_google', 'mock_instagram')));--> statement-breakpoint
ALTER TABLE "oauth_states" ADD CONSTRAINT "oauth_states_provider_chk" CHECK ("oauth_states"."provider" in ('mock_threads', 'threads', 'mock_google', 'mock_instagram'));--> statement-breakpoint
ALTER TABLE "remote_steps" ADD CONSTRAINT "remote_steps_kind_chk" CHECK ("remote_steps"."kind" in ('container', 'publish', 'upload_session', 'video', 'ig_container', 'ig_publish'));--> statement-breakpoint
ALTER TABLE "remote_steps" ADD CONSTRAINT "remote_steps_kind_status_chk" CHECK (("remote_steps"."kind" = 'container' and "remote_steps"."status" in ('created', 'finished', 'error')) or ("remote_steps"."kind" = 'publish' and "remote_steps"."status" = 'published') or ("remote_steps"."kind" = 'upload_session' and "remote_steps"."status" in ('created', 'finished', 'expired', 'error')) or ("remote_steps"."kind" = 'video' and "remote_steps"."status" in ('uploaded', 'processed', 'error')) or ("remote_steps"."kind" = 'ig_container' and "remote_steps"."status" in ('created', 'finished', 'error')) or ("remote_steps"."kind" = 'ig_publish' and "remote_steps"."status" = 'published'));